export const ROLE_PERMISSIONS = {
  MANAGER: [
    'PRODUCT_READ',
    'PRODUCT_WRITE',
    'CATEGORY_WRITE',
    'REPORT_READ',
    'USER_MANAGE',
    'INVENTORY_TRANSACTION_CREATE',
    'INVENTORY_READ',
  ],
  STAFF: [
    'PRODUCT_READ',
    'INVENTORY_TRANSACTION_CREATE',
    'INVENTORY_READ',
  ],
} as const;
