export const ROLE = {
  MANAGER: 'MANAGER',
  STAFF: 'STAFF',
} as const;

export const PERMISSION = {
  PRODUCT_READ: 'PRODUCT_READ',
  PRODUCT_WRITE: 'PRODUCT_WRITE',
  CATEGORY_WRITE: 'CATEGORY_WRITE',
  REPORT_READ: 'REPORT_READ',
  USER_MANAGE: 'USER_MANAGE',
  INVENTORY_TRANSACTION_CREATE: 'INVENTORY_TRANSACTION_CREATE',
  INVENTORY_READ: 'INVENTORY_READ',
} as const;
