import { ROLE, PERMISSION } from './role-permission.constant.js';

import type { AppRole, AppPermission } from './app-role-permission.type.js';

export const ROLE_PERMISSIONS: Record<AppRole, AppPermission[]> = {
  [ROLE.MANAGER]: [
    PERMISSION.PRODUCT_READ,
    PERMISSION.PRODUCT_WRITE,

    PERMISSION.CATEGORY_READ,
    PERMISSION.CATEGORY_WRITE,

    PERMISSION.INVENTORY_READ,
    PERMISSION.INVENTORY_TRANSACTION_CREATE,
    PERMISSION.INVENTORY_ADJUST,

    PERMISSION.REPORT_READ,

    PERMISSION.USER_READ,
    PERMISSION.USER_MANAGE,

    PERMISSION.STORE_READ,
    PERMISSION.STORE_WRITE,

    PERMISSION.INVENTORY_READ,
    PERMISSION.INVENTORY_WRITE,
  ],

  [ROLE.STAFF]: [
    PERMISSION.STORE_READ,

    PERMISSION.PRODUCT_READ,

    PERMISSION.CATEGORY_READ,

    PERMISSION.INVENTORY_READ,
    PERMISSION.INVENTORY_TRANSACTION_CREATE,
  ],
};
