export const ROLE = {
  MANAGER: 'MANAGER',
  STAFF: 'STAFF',
} as const;

export const PERMISSION = {
  PRODUCT_READ: 'PRODUCT_READ',
  PRODUCT_WRITE: 'PRODUCT_WRITE',
  CATEGORY_READ: 'CATEGORY_READ',
  CATEGORY_WRITE: 'CATEGORY_WRITE',
  REPORT_READ: 'REPORT_READ',
  STORE_READ: 'STORE_READ',
  STORE_WRITE: 'STORE_WRITE',
  USER_READ: 'USER_READ',
  USER_MANAGE: 'USER_MANAGE',
  INVENTORY_ADJUST: 'INVENTORY_ADJUST',
  INVENTORY_TRANSACTION_CREATE: 'INVENTORY_TRANSACTION_CREATE',
  INVENTORY_READ: 'INVENTORY_READ',
  INVENTORY_WRITE: 'INVENTORY_WRITE',
  AUDIT_LOG_READ: 'AUDIT_LOG_READ',
  AUDIT_LOG_WRITE: 'AUDIT_LOG_WRITE',
  STORE_MEMBER_READ: 'STORE_MEMBER_READ',
  STORE_MEMBER_WRITE: 'STORE_MEMBER_WRITE',
  STORE_MEMBER_DELETE: 'STORE_MEMBER_DELETE',
} as const;
