export const ERROR_CODE = {
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
  PRODUCT_HAS_NO_PACKAGE: 'PRODUCT_HAS_NO_PACKAGE',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
