// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbEzOo9x2p4G9IaRwhYmlep5TXt-I5qvo',
    appId: '1:38888872312:web:2d760312070c4472ba508d',
    messagingSenderId: '38888872312',
    projectId: 'storixapp-2026',
    authDomain: 'storixapp-2026.firebaseapp.com',
    storageBucket: 'storixapp-2026.firebasestorage.app',
    measurementId: 'G-J02B0PP2TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABWzxYnCQM4DSSZFzhOXBP-zuxdBzN56k',
    appId: '1:38888872312:android:4801deab2d620c37ba508d',
    messagingSenderId: '38888872312',
    projectId: 'storixapp-2026',
    storageBucket: 'storixapp-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHsFneRJila0t6AhpxQrToT0HTTYvA8ow',
    appId: '1:38888872312:ios:4294644e653e7efcba508d',
    messagingSenderId: '38888872312',
    projectId: 'storixapp-2026',
    storageBucket: 'storixapp-2026.firebasestorage.app',
    iosBundleId: 'com.group21.storix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHsFneRJila0t6AhpxQrToT0HTTYvA8ow',
    appId: '1:38888872312:ios:ac8a42fb4f0bbf3fba508d',
    messagingSenderId: '38888872312',
    projectId: 'storixapp-2026',
    storageBucket: 'storixapp-2026.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbEzOo9x2p4G9IaRwhYmlep5TXt-I5qvo',
    appId: '1:38888872312:web:c33d8a7ae3a0bb87ba508d',
    messagingSenderId: '38888872312',
    projectId: 'storixapp-2026',
    authDomain: 'storixapp-2026.firebaseapp.com',
    storageBucket: 'storixapp-2026.firebasestorage.app',
    measurementId: 'G-1226R7QKG2',
  );
}
